spring:
  datasource:
    rds:
      url: jdbc:mysql://db-mysql.dian-stable.com/gamon
      username: dev_admin
      password: wcN4XJJMoHK6uciG
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 10
      min-idle: 5
  redis:
    host: r-2zehnriold4wekq31z.redis.rds.aliyuncs.com
    password: Kongge789
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        max-wait: 16
        max-active: 16
        max-idle: 16
        min-idle: 1
      shutdown-timeout: 10000ms  # 关闭超时时间
  mail:
    host: 'smtp.126.com'
    port: 465
    protocol: 'smtps'
    username: 'paijitang2022'
    password: 'NMJZTXCGDJEAQVLF'
    default-encoding: 'UTF-8'
    properties:
      mail:
        smtp:
          from: 'paijitang2022@126.com'
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  tomcat:
    mbeanregistry:
      enabled: true
    accesslog:
      buffered: true
      enabled: true
      directory: /Users/wanggong/home/admin/logs/
      file-date-format: .yyyyMMdd
      pattern: "%a||%t||%{Host}i||%p||%m||%U||%H||%q||%s||%b||%{Referer}i||%{User-Agent}i||%{X-Real-Ip}i||%{X-Forwarded-For}i||%D"
      prefix: tomcat_access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log

management:
  server:
    port: 8888
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  trace:
    http:
      enabled: true
  health:
    mail:
      enabled: false

logging.file:
  path: /home/admin/logs/${spring.application.name}
  name: /home/admin/logs/${spring.application.name}/${spring.application.name}.log

#local需要的配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: false
    service-url:
      defaultZone: https://eureka.dian-stable.com/eureka
  instance:
    non-secure-port: 8080
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      instance-id: ${eureka.instance.instance-id}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3

ribbon:
  ServerListRefreshInterval: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  SocketTime: 6000